import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NewsletterSection from "@/components/home/Footer";
import ShopAmHeader from "@/components/shared/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const terminaFont = localFont({
  src: [
    {
      path: "../public/fonts/termina/TerminaTest-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/termina/TerminaTest-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/termina/TerminaTest-Demi.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/termina/TerminaTest-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-termina",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${terminaFont.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="antialiased">
        <ShopAmHeader />
        {children}
        <NewsletterSection />
      </body>
    </html>
  );
}
